[build]
  base = "Frontend"  # Capital "F" to match the actual folder name
  command = "npm run build"
  publish = "dist"  # Ensure build output goes into "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
